#!/bin/bash
#
# How to run
# cd $imgui4xp Repo
# ./build_imgui4xp_all_OnLinux_WithCmake

rm -r imgui4xp/win_x64/*.xpl
rm -r imgui4xp/lin_x64/*.xpl
rm -r imgui4xp/mac_x64/*.xpl


# Windows build

 rm -r build/*
 cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
 cmake --build ./build -v
 cp ./build/imgui4xp.xpl ./imgui4xp/win_x64/imgui4xp.xpl
 
 
 # Linux build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build -v
cp ./build/imgui4xp.xpl ./imgui4xp/lin_x64/imgui4xp.xpl


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-x86_64-11.3.cmake
cmake --build ./build -v
cp ./build/imgui4xp.xpl ./imgui4xp/mac_x64/imgui4xp.xpl


cp imgui_demo.jpg imgui4xp/

exec $SHELL
#

